# Netlify configuration for Lawncha Libre

[build]
  command = "npm run build"
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "22.20.0"
    # Configure secrets scanning - tell Netlify these VITE_ prefixed keys are public and safe
    SECRETS_SCAN_OMIT_KEYS = "VITE_CONVEX_URL,VITE_CLERK_PUBLISHABLE_KEY,VITE_CLERK_FRONTEND_API_URL,VITE_UPLOADTHING_URL,VITE_UPLOADTHING_TOKEN"

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

